### PR TITLE
Updated all issue templates

### LINKED ISSUE #24: Issue Template Updates for Figma link
### Current Behavior
The project's current issue templates are missing an open invitation link where new contributors can join the community's Figma team and view user interface designs and other UX projects.

### Desired Situation
Each template that has a reference to Figma in its resources section should an invite link added.

### Implementation 
```
- 🎨 Wireframes and [designs for Layer5](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
```

**Acceptance Tests**
All references to Figma include the "open invite" link.

---
**Implementation**

**Mockups**

**Acceptance Tests**

### PR DESCRIPTION
**Pull request by Sankhadip-Roy**
**Description**
Updated all issue templates with the contributing resources mentioned in Layer5.io's issue_templates
This PR fixes #24

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by thisiskaransgit — COMMENTED** [review]
Hey @Sankhadip-Roy, please incorporate the same changes that I suggested at https://github.com/layer5io/meshery-smi-conformance-action/pull/47

**Review by leecalcote — APPROVED** [review]
These look great. I don’t see any mishaps in their refactoring.

**Comment by leecalcote** [comment]
Thanks, @Sankhadip-Roy!

**Comment by leecalcote** [comment]
@Sankhadip-Roy, it looks like we have a bug in the welcome config yaml - in case you’re interested in working on it.

**Comment by Sankhadip-Roy** [comment]
> @Sankhadip-Roy, it looks like we have a bug in the welcome config yaml - in case you’re interested in working on it.
Yes absolutely, @leecalcote 
Are you talking about the congrats image not showing in the welcome bot's comment.
If that is the case:
---
image

I think here the link of the png should be
from this: https://raw.githubusercontent.com/layer5io/meshery/master/.github/welcome/Layer5-celebration.png
to this: https://raw.githubusercontent.com/layer5io/meet/master/.github/welcome/Layer5-celebration.png

**Comment by leecalcote** [comment]
You're right. Directly to PR will work.

**Pull request merged**
