### PR TITLE
Update documentation.md

### LINKED ISSUE #24: Issue Template Updates for Figma link
### Current Behavior
The project's current issue templates are missing an open invitation link where new contributors can join the community's Figma team and view user interface designs and other UX projects.

### Desired Situation
Each template that has a reference to Figma in its resources section should an invite link added.

### Implementation 
```
- 🎨 Wireframes and [designs for Layer5](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
```

**Acceptance Tests**
All references to Figma include the "open invite" link.

---
**Implementation**

**Mockups**

**Acceptance Tests**

### PR DESCRIPTION
**Pull request by Sankhadip-Roy**
**Description**
Updated the figma link in the resources section of the issue templates.
Resources section was only present in the documentation.md 

This PR fixes #24

**Notes for Reviewers**
Do I have to add the link to other issue templates?

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
Meshery UI isn't worked on here, but Layer5 Designs are. 

@Chadha93

**Comment by leecalcote** [comment]
@thisiskaransgit make sure that your issues describe the correct design file.

**Comment by Sankhadip-Roy** [comment]
> Meshery UI isn't worked on here, but Layer5 Designs are.
> 
> @Chadha93

What should I do?

**Comment by Sankhadip-Roy** [comment]
> > > Meshery UI isn't worked on here, but Layer5 Designs are.
> > > @Chadha93
> > 
> > 
> > What should I do?
> 
> @Sankhadip-Roy Use this link for Layer5 Figma: https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?type=design&t=lQTTfDw1sfu2xPNT-6

image
Should we have to change these also?

**Comment by thisiskaransgit** [comment]
@Sankhadip-Roy, yes please, this hasn't been updated for a time now.
Update all existing issue templates with the contributing resources mentioned in Layer5.io's [issue_templates](https://github.com/layer5io/layer5/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#contributor-resources-and-handbook)

**Pull request closed without merging**
