### PR TITLE
Added updated meeting links

### PR DESCRIPTION
**Pull request by sumana-19**
Added the updated links to README

### CODE REVIEW

**Comment by leecalcote** [comment]
Thanks for this, @sumana-19. I think there's slight confusion on the ask in the original issue. I know, @chandrashritii, will assist in clarifying. 

It's good to get this README updated. I believe that the other issue intends to refer to https://github.com/layer5io/layer5/blob/master/README.md

**Review by leecalcote — APPROVED** [review]
Much appreciated, @sumana-19. 👍

**Comment by leecalcote** [comment]
Thanks again, @sumana-19   you’re most welcome to join the Layer5 community - https://layer5.io/community

**Comment by sumana-19** [comment]
Thanks, @leecalcote !

**Pull request merged**
